FROM alpine:3.21

WORKDIR /workspace
ENV DEBIAN_FRONTEND=noninteractive
RUN apk --no-cache --update add python3 py3-pip gcc ffmpeg

COPY requirements.txt .
## --break-system-packages: alphineではapkを使ってpipパッケージを導入する変更が行われたことに対する対処
RUN pip3 install --break-system-packages --no-cache --upgrade -r requirements.txt
COPY src/ .
WORKDIR /download
ENV TZ=Asia/Tokyo
EXPOSE 5000
ENTRYPOINT ["python3","-u","/workspace/main.py"]