version: '3'

services:
  redis:
    image: redis
    restart: always

  api:
    build:
      dockerfile: ./Dockerfile.api
    depends_on:
      - redis
    environment:
      RQ_REDIS_URL: redis://redis
    ports:
      - 5000:5000
    restart: always

  worker:
    build:
      dockerfile: ./Dockerfile.worker
    depends_on:
      - redis
    environment:
      RQ_REDIS_URL: redis://redis
    volumes:
      - /mnt/video:/download
    working_dir: /download
    restart: always
