FROM alpine:3.18

WORKDIR /workspace
ENV DEBIAN_FRONTEND=noninteractive
RUN apk --no-cache --update add python3 py3-pip gcc ffmpeg mutagen

COPY requirements.txt .
RUN pip3 install --no-cache --upgrade -r requirements.txt
COPY src/ .
WORKDIR /download
ENV TZ=Asia/Tokyo
EXPOSE 5000
ENTRYPOINT ["python3","-u","/workspace/worker.py"]